name: CI

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project arduino-remote
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
